#!/bin/bash

DAEMON=/usr/bin/python
ARGS="/RPi-OBABP/src/obabp2.py"
PIDFILE=/var/run/obabp2.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user www-data --group www-data \
        -b --make-pidfile \
        --chuid www-data \
        --exec $DAEMON $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/obabp {start|stop}"
    exit 1
    ;;
esac

exit 0
